server:
  port: 18000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.214.128:8848
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: apple
        uri: lb://apple
        predicates:
        - Path=/apple/**
        filters:
        - StripPrefix=1
      - id: banana
        uri: lb://banana
        predicates:
        - Path=/banana/**
        filters:
        - StripPrefix=1
  data:
    elasticsearch:
      cluster-nodes: 192.168.214.128:9300
      cluster-name: modnim_node